### ISSUE TITLE
internal server error when load model "OpenCSG/csg-wukong-1B" from opencsg.com

### ISSUE THREAD

**Issue by Rader** [OpenCSGs/csghub-sdk#4]
error:

```
Traceback (most recent call last):
  File "/private/tmp/csghub-sdk-demo/main.py", line 22, in <module>
    model = AutoModelForCausalLM.from_pretrained(repo_id)
  File "/Users/leida/miniconda3/envs/csghub-sdk/lib/python3.10/site-packages/pycsghub/repo_reader/model/huggingface/model_auto.py", line 19, in from_pretrained
    path = Path(snapshot_download(pretrained_model_name_or_path, token=token))
  File "/Users/leida/miniconda3/envs/csghub-sdk/lib/python3.10/site-packages/pycsghub/snapshot_download.py", line 55, in snapshot_download
    repo_info = utils.get_repo_info(repo_id,
  File "/Users/leida/miniconda3/envs/csghub-sdk/lib/python3.10/site-packages/pycsghub/utils.py", line 142, in get_repo_info
    return method(
  File "/Users/leida/miniconda3/envs/csghub-sdk/lib/python3.10/site-packages/pycsghub/utils.py", line 218, in model_info
    r.raise_for_status()
  File "/Users/leida/miniconda3/envs/csghub-sdk/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://hub-stg.opencsg.com/hf/api/models/OpenCSG/csg-wukong-1B/revision/main
```

code:
```Python
import os
from pycsghub.repo_reader import AutoModelForCausalLM

os.environ[
    "CSG_TOKEN"
] = "[MY_TOKEN]"

repo_id = "OpenCSG/csg-wukong-1B"
model = AutoModelForCausalLM.from_pretrained(repo_id)
```

**Comment by luckylumiere** [comment]
@Rader fixed

**Comment by SeanHH86** [comment]
Cannot reproduce this issue.
